### ISSUE TITLE
Add 1.8

### ISSUE THREAD

**Issue by phase** [Dimensions/mc-dev#1]
We need to add 1.8 to this. I've created branches for the most recent releases, so we can organize this more.

**Comment by wgaylord** [comment]
Make all the SRC actually use MCP naming too....

**Comment by wgaylord** [comment]
When I get home I can do this. (Any make all the versions listed MCP Style with bukkit on its own branches.)

**Comment by phase** [comment]
+1

**Comment by wgaylord** [comment]
I still need to do this....
